import type { Simulation } from "@/types";

export const simulations: Simulation[] = [
  {
    id: 1,
    slug: "product-strategy",
    title: "Product Strategy",
    company: "Nexus Bank",
    industry: "Financial Services",
    type: "Strategy",
    difficulty: "Foundation",
    time: "45 mins",
    description:
      "Define the product strategy for a new startup banking account. Understand market needs, map the competitive landscape, and recommend a direction to the executive team.",
  },
  {
    id: 2,
    slug: "customer-research-and-insights",
    title: "Customer Research and Insights",
    company: "Vitara Health",
    industry: "HealthTech",
    type: "Discovery",
    difficulty: "Foundation",
    time: "45 mins",
    description:
      "Conduct user research for a new health monitoring feature. Develop an interview guide, identify user personas, and synthesise your findings into actionable insights.",
  },
  {
    id: 3,
    slug: "ideation-and-prioritisation",
    title: "Ideation and Prioritisation",
    company: "Stackly",
    industry: "SaaS",
    type: "Strategy",
    difficulty: "Foundation",
    time: "45 mins",
    description:
      "Your team has generated dozens of product ideas with limited resources. Prioritise them using structured frameworks and defend your decisions to stakeholders.",
  },
  {
    id: 4,
    slug: "agile-product-development",
    title: "Agile Product Development",
    company: "Orbis Digital",
    industry: "Software Development",
    type: "Delivery",
    difficulty: "Practitioner",
    time: "60 mins",
    description:
      "Manage a cross-functional Agile team facing scope creep on a critical feature. Resolve the issue without disrupting the sprint or the team dynamic.",
  },
  {
    id: 5,
    slug: "ux-and-ui-design",
    title: "UX and UI Design",
    company: "Movo",
    industry: "Consumer Mobile",
    type: "Discovery",
    difficulty: "Practitioner",
    time: "60 mins",
    description:
      "Lead a mobile app redesign. Create a roadmap and product strategy that meets specific user needs while working effectively with the design team.",
  },
  {
    id: 6,
    slug: "pricing-strategies",
    title: "Pricing Strategies",
    company: "Lumora",
    industry: "EdTech",
    type: "Strategy",
    difficulty: "Practitioner",
    time: "60 mins",
    description:
      "Your company is switching from a freemium model to tiered pricing. Develop a pricing strategy, model the impact, and justify the change to leadership.",
  },
  {
    id: 7,
    slug: "product-launch",
    title: "Product Launch",
    company: "Crest Consumer",
    industry: "Consumer Goods",
    type: "Go-to-Market",
    difficulty: "Practitioner",
    time: "75 mins",
    description:
      "Plan and execute a go-to-market strategy for a new product. Define your marketing channels, customer segments, and post-launch success metrics.",
  },
  {
    id: 8,
    slug: "metrics-and-analytics",
    title: "Metrics and Analytics",
    company: "Dataflow",
    industry: "Analytics",
    type: "Analysis",
    difficulty: "Practitioner",
    time: "60 mins",
    description:
      "Analyse KPIs following a product launch. Identify performance gaps, propose data-driven improvements, and present your recommendations clearly.",
  },
  {
    id: 9,
    slug: "stakeholder-management",
    title: "Stakeholder Management",
    company: "Bridgepoint",
    industry: "Infrastructure",
    type: "Stakeholder",
    difficulty: "Practitioner",
    time: "75 mins",
    description:
      "Navigate multiple stakeholders with conflicting interests. Build a communication plan that keeps everyone aligned without compromising the product vision.",
  },
  {
    id: 10,
    slug: "customer-acquisition",
    title: "Customer Acquisition",
    company: "Spark Retail",
    industry: "E-commerce",
    type: "Strategy",
    difficulty: "Practitioner",
    time: "60 mins",
    description:
      "Develop a customer acquisition strategy for a D2C brand entering a crowded market. Define your channels, cost per acquisition targets, and growth levers.",
  },
  {
    id: 11,
    slug: "go-to-market-strategy",
    title: "Go-to-Market Strategy",
    company: "Vanta Global",
    industry: "International Retail",
    type: "Go-to-Market",
    difficulty: "Advanced",
    time: "90 mins",
    description:
      "Lead the international expansion of a retail product into two new markets. Develop the full GTM strategy including localisation, pricing, and channel selection.",
  },
  {
    id: 12,
    slug: "product-market-fit",
    title: "Product Market Fit",
    company: "Peakform",
    industry: "Sports Technology",
    type: "Discovery",
    difficulty: "Advanced",
    time: "90 mins",
    description:
      "Assess whether a sports performance product has achieved product market fit. Analyse signals, identify gaps, and recommend a path to stronger retention and growth.",
  },
  {
    id: 13,
    slug: "roadmap-development",
    title: "Roadmap Development",
    company: "Claros",
    industry: "Enterprise Software",
    type: "Strategy",
    difficulty: "Advanced",
    time: "90 mins",
    description:
      "Build a 12 month product roadmap for an enterprise software platform. Balance technical debt, customer requests, and strategic initiatives across competing priorities.",
  },
  {
    id: 14,
    slug: "pitch-deck-creation",
    title: "Pitch Deck Creation",
    company: "Founded",
    industry: "Venture Capital",
    type: "Strategy",
    difficulty: "Advanced",
    time: "90 mins",
    description:
      "Create a compelling pitch deck for a new product concept. Structure your narrative, validate your assumptions, and present a convincing case to a panel of investors.",
  },
];
